const fs = require("fs");

const topics = [
  "Digital Marketing Strategy",
  "AI Automation for Business",
  "Passive Income Online",
  "Content Marketing Trends",
  "Remote Work Productivity"
];

const randomTopic = topics[Math.floor(Math.random() * topics.length)];
const today = new Date().toISOString().split("T")[0];
const hour = new Date().getHours();
const folder = hour < 12 ? "morning" : "night";

const slug = randomTopic.toLowerCase().replace(/ /g, "-");
const fileName = `${today}-${slug}.md`;
const filePath = `./${folder}/${fileName}`;

const metaDescription = `${randomTopic} complete guide for beginners. Learn strategies, tips, and practical implementation steps.`;

// Internal link generator
function getInternalLink() {
  const files = fs.readdirSync(`./${folder}`);
  const mdFiles = files.filter(f => f.endsWith(".md"));
  if (mdFiles.length === 0) return "";
  const randomFile = mdFiles[Math.floor(Math.random() * mdFiles.length)];
  return `\n\nRelated article: [Read more](./${randomFile})\n`;
}

const content = `
---
title: "${randomTopic} Guide ${today}"
description: "${metaDescription}"
date: "${today}"
author: "Mimpact Engine"
---

# ${randomTopic} – Complete Guide

## Introduction

${randomTopic} is rapidly transforming the digital landscape. Businesses and individuals who understand this shift gain competitive advantage.

## Why ${randomTopic} Matters

- Improves efficiency  
- Creates scalable systems  
- Enhances long-term growth  

## Step-by-Step Implementation

### 1. Understand the Foundation
Start by analyzing your current strategy and identifying improvement areas.

### 2. Apply Practical Execution
Implement small consistent improvements instead of massive changes.

### 3. Measure and Optimize
Track metrics and refine continuously.

## Common Mistakes to Avoid

- Ignoring data
- Lack of consistency
- Overcomplicating systems

## Future Outlook

${randomTopic} will continue evolving as technology advances. Early adoption is key.

## Conclusion

Mastering ${randomTopic} requires clarity, strategy, and execution discipline.

${getInternalLink()}

---

*This article was automatically generated by Mimpact Content Engine.*
`;

fs.writeFileSync(filePath, content);

console.log("SEO content generated:", filePath);
